version: '3.9'
services:
  library_app:
    image: webjsmaster/app_image
    container_name: app_container
    restart: always
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT_POSTGRES}
      - TYPEORM_HOST=library_db
    depends_on:
      - library_db
    volumes:
      - ./:/usr/app
      - node_modules:/usr/app/node_modules
    networks:
      - library_bridge
  library_db:
    container_name: db_container
    image: postgres:15.1-alpine
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT_POSTGRES}:${TYPEORM_PORT_POSTGRES}
    networks:
      - library_bridge
volumes:
  library_db:
  node_modules:
networks:
  library_bridge:
    driver: bridge
    name: 'library_bridge'